Disable cert chain
google/libsxg pull request #71
Opened 2021-01-06 21:17 UTC by cpapazian

https://github.com/google/libsxg/issues/66

2021-01-06 23:09 UTC, cpapazian commented
note that this is based off the branch from https://github.com/google/libsxg/pull/68

2021-01-09 00:11 UTC, twifkak requested changes
Thanks again for the improvements.

2021-01-09 00:11 UTC, twifkak commented on CMakeLists.txt
> +configure_file(
Instead of file generation I'd prefer:

```
if (SXG_WITHOUT_CERT_CHAIN)
  add_compile_definitions(LIBSXG_WITHOUT_CERT_CHAIN)
endif ()
```

Proof of concept at https://github.com/twifkak/libsxg/commit/ddbac5896ba2f1c010c9a6f2526c3207ab22a607. WDYT?

2021-01-09 05:52 UTC, cpapazian commented on CMakeLists.txt
> +configure_file(
will this won't work if libsxg is included in another project? we'd need to know to define `LIBSXG_WITHOUT_CERT_CHAIN`, right?

2021-01-11 18:55 UTC, cpapazian commented on CMakeLists.txt
>  option (SXG_BUILD_EXECUTABLES "Build gensxg/gencertchain executables" ON)
had trouble extending the cmake_dependent_option, but an ordinary if condition seems to accomplish the same

2021-01-14 18:30 UTC, cpapazian commented on CMakeLists.txt
> +configure_file(
@twifkak i was able to confirm that the `add_compile_definitions` approach will not work for us. the issue is that the compile definition does not trigger when libsxg is included in another project: 
```
In file included from pinterest/filters/http/sxg/config.cc:11:
In file included from ./pinterest/filters/http/sxg/filter.h:10:
In file included from bazel-out/k8-fastbuild/bin/pinterest/filters/http/sxg/libsxg/include/libsxg.h:22:
bazel-out/k8-fastbuild/bin/pinterest/filters/http/sxg/libsxg/include/libsxg/sxg_cert_chain.h:20:10: fatal error: 'openssl/ct.h' file not found
#include <openssl/ct.h>
         ^~~~~~~~~~~~~~
1 error generated.
INFO: Elapsed time: 20.246s, Critical Path: 9.61s
INFO: 5 processes: 4 internal, 1 local.
FAILED: Build did NOT complete successfully
//pinterest/filters/http/sxg:sxg_test                           FAILED TO BUILD
```
in the above example we are using `libsxg.a` with the installed `libsxg.h` header file

2021-01-15 20:40 UTC, twifkak commented on CMakeLists.txt
> +configure_file(
Thanks for confirming. I wanted to validate that but got pulled into other priorities. This works for me, then.

2021-01-15 20:54 UTC, twifkak commented on CMakeLists.txt
>  option (SXG_BUILD_EXECUTABLES "Build gensxg/gencertchain executables" ON)
OK, works for me. For cmake_dependent_option, I think you'd need to quote the condition argument like:

```
cmake_dependent_option (SXG_BUILD_EXECUTABLES "Build gensxg/gencertchain executables" ON
                        "SXG_BUILD_SHARED AND SXG_WITH_CERT_CHAIN" OFF)
```

but I haven't tried it.

(In CMake, undefined variable references have a value of `OFF`? That's a little bit terrifying.)

2021-01-15 20:56 UTC, twifkak approved these changes
Thanks for the changes & comments. Merging.

2021-01-15 21:04 UTC, merged